# quality scores, VAF, and sample fraction are all numbers between 0 and 1
# read counts are any number
HipSTR:
  # all parameters are numbers
  nonA.min.qual: 0
  nonA.min.mallreads: 0
  nonA.min.allele.mallreads: 0
  nonA.min.mvaf: 0.2
  nonA.min.allreads: 0
  nonA.min.allele.allreads: 0
  nonA.min.avaf: 0
  nonA.max.stutter.frac: 0.13
  nonA.max.flankindel.frac: 0.13
  nonA.min.gldiff: 25
  nonA.min.mean.mallreads: 0
  nonA.min.mean.allreads: 0
  nonA.min.mean.qual: 0.95
  nonA.min.sample.frac: 0
  A.min.qual: 0
  A.min.mallreads: 0
  A.min.allele.mallreads: 0
  A.min.mvaf: 0.3
  A.min.allreads: 0
  A.min.allele.allreads: 0
  A.min.avaf: 0
  A.max.stutter.frac: 1
  A.max.flankindel.frac: 0.13
  A.min.gldiff: 1
  A.min.mean.mallreads: 0
  A.min.mean.allreads: 0
  A.min.mean.qual: 0.85
  A.min.sample.frac: 0
GangSTR:
  # all parameters are numbers
  nonA.min.qual: 0
  nonA.min.total.reads: 0
  nonA.min.allele.reads: 80
  nonA.min.vaf: 0
  nonA.min.mean.total.reads: 0
  nonA.min.mean.qual: 1
  nonA.min.sample.frac: 0
  A.min.qual: 0
  A.min.total.reads: 0
  A.min.allele.reads: 15
  A.min.vaf: 0.4
  A.min.mean.total.reads: 0
  A.min.mean.qual: 0.5
  A.min.sample.frac: 0
EH:
  # all parameters are numbers
  nonA.min.total.reads: 0
  nonA.min.allele.reads: 60
  nonA.min.vaf: 0.5
  nonA.max.vaf: 2.5
  nonA.min.lc: 0
  nonA.min.mean.total.reads: 0
  nonA.min.sample.frac: 0
  A.min.total.reads: 0
  A.min.allele.reads: 0
  A.min.vaf: 0
  A.max.vaf: 999
  A.min.lc: 0
  A.min.mean.total.reads: 0
  A.min.sample.frac: 0
ensemble:
  # fill in "HipSTR", "GangSTR", "EH", or "no_caller"
  # caller.one cannot be filled in with "no_caller"
  # caller.two can only be "no_caller" if caller.three is also "no_caller"
  # caller.three can always be "no_caller"
  nonA.caller.one: HipSTR
  nonA.caller.two: GangSTR
  nonA.caller.three: EH
  A.caller.one: GangSTR
  A.caller.two: HipSTR
  A.caller.three: no_caller
sample:
  # trio ID from Nextflow pipeline
  trio: your_trio
  # sample IDs from Nextflow pipeline
  father: individual_1
  mother: individual_2
  child: individual_3
  # fill in "M" or "F"
  sex.of.child: F
